### ISSUE TITLE
Use embeds for the q!status command

### ISSUE THREAD

**Issue by ThaTiemsz** [BlobEmoji/queuebot#26] opened 2017-12-16 20:11 UTC
Currently this command is not sanitized and will mention the users, so easiest would be to move the info into a rich embed, that way the mentions are still clickable.

![image](https://user-images.githubusercontent.com/18150845/34073937-96aaa8ae-e2a5-11e7-863b-07acd808b3c6.png)

**Comment by slice** [comment] 2017-12-16 20:17
Duplicate of #23.

**Closed by slice** 2017-12-16 20:17 UTC
